// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structdef.proto

package goserbench

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoBufA struct {
	ID                   *int64   `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Tag                  *uint64  `protobuf:"varint,2,req,name=Tag" json:"Tag,omitempty"`
	Timestamp            *int64   `protobuf:"varint,3,req,name=Timestamp" json:"Timestamp,omitempty"`
	Frames               []uint64 `protobuf:"varint,4,rep,name=Frames" json:"Frames,omitempty"`
	GID                  *int64   `protobuf:"varint,5,req,name=GID" json:"GID,omitempty"`
	TxID                 *uint64  `protobuf:"varint,6,req,name=TxID" json:"TxID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoBufA) Reset()         { *m = ProtoBufA{} }
func (m *ProtoBufA) String() string { return proto.CompactTextString(m) }
func (*ProtoBufA) ProtoMessage()    {}
func (*ProtoBufA) Descriptor() ([]byte, []int) {
	return fileDescriptor_structdef_23f852e8ad7b2db6, []int{0}
}
func (m *ProtoBufA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBufA.Unmarshal(m, b)
}
func (m *ProtoBufA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBufA.Marshal(b, m, deterministic)
}
func (dst *ProtoBufA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBufA.Merge(dst, src)
}
func (m *ProtoBufA) XXX_Size() int {
	return xxx_messageInfo_ProtoBufA.Size(m)
}
func (m *ProtoBufA) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBufA.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBufA proto.InternalMessageInfo

func (m *ProtoBufA) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ProtoBufA) GetTag() uint64 {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return 0
}

func (m *ProtoBufA) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ProtoBufA) GetFrames() []uint64 {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *ProtoBufA) GetGID() int64 {
	if m != nil && m.GID != nil {
		return *m.GID
	}
	return 0
}

func (m *ProtoBufA) GetTxID() uint64 {
	if m != nil && m.TxID != nil {
		return *m.TxID
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoBufA)(nil), "goserbench.ProtoBufA")
}

func init() { proto.RegisterFile("structdef.proto", fileDescriptor_structdef_23f852e8ad7b2db6) }

var fileDescriptor_structdef_23f852e8ad7b2db6 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0x49, 0x49, 0x4d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xcf, 0x2f,
	0x4e, 0x2d, 0x4a, 0x4a, 0xcd, 0x4b, 0xce, 0x50, 0xea, 0x64, 0xe4, 0xe2, 0x0c, 0x00, 0x89, 0x3a,
	0x95, 0xa6, 0x39, 0x0a, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x69, 0x30, 0x07,
	0x31, 0x79, 0xba, 0x08, 0x09, 0x70, 0x31, 0x87, 0x24, 0xa6, 0x4b, 0x30, 0x29, 0x30, 0x69, 0xb0,
	0x04, 0x81, 0x98, 0x42, 0x32, 0x5c, 0x9c, 0x21, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05,
	0x12, 0xcc, 0x60, 0x85, 0x08, 0x01, 0x21, 0x31, 0x2e, 0x36, 0xb7, 0xa2, 0xc4, 0xdc, 0xd4, 0x62,
	0x09, 0x16, 0x05, 0x66, 0x0d, 0x96, 0x20, 0x28, 0x0f, 0x64, 0x8e, 0xbb, 0xa7, 0x8b, 0x04, 0x2b,
	0x58, 0x3d, 0x88, 0x29, 0x24, 0xc4, 0xc5, 0x12, 0x52, 0xe1, 0xe9, 0x22, 0xc1, 0x06, 0x36, 0x1a,
	0xcc, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xa3, 0x0a, 0xb1, 0xa9, 0x00, 0x00, 0x00,
}
